### ISSUE TITLE
No session factory registered for the given session options

### ISSUE THREAD

**Issue by mengwanguc** [SymbioticLab/Salus#31]
Hello,

I got the error when I tried to submit a TF job to the image:

_No session factory registered for the given session options: {target: "zrpc://tcp://localhost:5501" config: device_count { key: "CPU" value: 1 } device_count { key: "GPU" value: 2 } gpu_options { visible_device_list: "0,1" experimental { } }} Registered factories are {DIRECT_SESSION, GRPC_SESSION}._

I used "zrpc://tcp://localhost:5501" as the session target.

Any idea on what's going wrong?

**Comment by Aetf** [comment]
You need the customized version of tensorflow: https://github.com/SymbioticLab/tensorflow-salus
